import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { Script } from 'node:vm';

export function buildStaticBundle({ model, pdf, app }) {
  // Named import aliases must survive flattening the modules into one script.
  const application = app.replace(/^import\s+\{([^}]+)\}\s+from\s+['"][^'"]+['"];\r?\n/gm, (_, bindings) =>
    bindings.split(',').flatMap(binding => {
      const alias = binding.trim().match(/^(\w+)\s+as\s+(\w+)$/);
      return alias ? [`const ${alias[2]} = ${alias[1]};\n`] : [];
    }).join('')
  );
  const bundle = `/* Generated by scripts/build-static.mjs from modular organizer sources. */\n(() => {\n${model.replaceAll('export ', '')}\n${pdf.replaceAll('export ', '')}\n${application}\n})();\n`;
  new Script(bundle);
  return bundle;
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const root = new URL('../public/', import.meta.url);
  const read = path => readFileSync(new URL(path, root), 'utf8');
  writeFileSync(new URL('app.bundle.js', root), buildStaticBundle({
    model: read('organizador/model.js'),
    pdf: read('organizador/pdf-import.js'),
    app: read('app.js')
  }));
}
